# Generated by Django 3.1.6 on 2021-02-08 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('giswebapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incidences',
            options={'verbose_name_plural': 'Incidences'},
        ),
    ]
