# Generated by Django 3.1.6 on 2021-03-13 09:33

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('giswebapp', '0003_auto_20210303_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidences',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(srid=32644),
        ),
    ]
