# Generated by Django 3.1.6 on 2021-03-13 10:00

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giswebapp', '0004_auto_20210313_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hostels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('country', models.CharField(max_length=254)),
                ('hostelid', models.CharField(max_length=254)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=32644)),
            ],
            options={
                'verbose_name_plural': 'Hostels',
            },
        ),
    ]
